In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
%matplotlib inline

In [2]:
diabetes = pd.read_csv('./diabetes.csv')

In [4]:
diabetes.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [5]:
d = diabetes.values

In [6]:
X = d[:,:-1]
Y = d[:,-1]

In [7]:
X

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [8]:
print(X.shape,Y.shape)

(768, 8) (768,)


In [9]:
Y

array([1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1.,
       1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0.,
       0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
       1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1.,
       1., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0.,
       0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 0., 0., 0., 0.

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.20)

In [11]:
ones = np.ones ((X_train.shape[0],1))
X_new_train = np.hstack((ones,X_train))
print(X_new_train)
print(X_new_train.shape)

[[1.00e+00 2.00e+00 1.55e+02 ... 3.87e+01 2.40e-01 2.50e+01]
 [1.00e+00 1.00e+00 1.17e+02 ... 3.45e+01 4.03e-01 4.00e+01]
 [1.00e+00 3.00e+00 9.90e+01 ... 2.18e+01 2.79e-01 2.60e+01]
 ...
 [1.00e+00 1.00e+00 8.90e+01 ... 3.12e+01 1.92e-01 2.30e+01]
 [1.00e+00 2.00e+00 1.29e+02 ... 2.80e+01 2.84e-01 2.70e+01]
 [1.00e+00 3.00e+00 1.21e+02 ... 3.60e+01 1.27e-01 2.50e+01]]
(614, 9)


In [12]:
Y_train.shape

(614,)

In [13]:
ones = np.ones ((X_test.shape[0],1))
X_new_test = np.hstack((ones,X_test))
print(X_new_test)
print(X_new_test.shape)

[[  1.      1.     77.    ...  33.3     1.251  24.   ]
 [  1.      4.     99.    ...  23.2     0.223  21.   ]
 [  1.     12.    151.    ...  41.8     0.742  38.   ]
 ...
 [  1.      1.    138.    ...  40.1     0.236  28.   ]
 [  1.      7.    102.    ...  37.2     0.204  45.   ]
 [  1.     11.     85.    ...  30.1     0.3    35.   ]]
(154, 9)


In [14]:
Y_train = Y_train.reshape((-1,1))
Y_test = Y_test.reshape((-1,1))

In [15]:
print(X_train.shape,X_test.shape)
print(X_new_train.shape,X_new_test.shape)
print(Y_train.shape,Y_test.shape)

(614, 8) (154, 8)
(614, 9) (154, 9)
(614, 1) (154, 1)


In [17]:
def sigmoid(x):
    return 1.0/(1.0 + np.exp(-x))

def hypothesis(X,theta):
    # X - entire array (m,n+1)
    # theta - np.array(n+1,1)
    return sigmoid(np.dot(X,theta))

def error(X,y,theta):

    hi = hypothesis(X,theta)
    e = -1*np.mean(y*np.log(hi)+(1-y)*np.log(1-hi))
    return e

def gradient(X,y,theta):

    hi = hypothesis(X,theta)
    grad = np.dot(X.T,(y-hi))
    return grad/X.shape[0]

def gradient_descent(X,y,lr=0.1,max_itr=500):
    n = X.shape[1]
    theta = np.zeros((n,1))
    
    error_list = []
    for i in range(max_itr):
        err = error(X,y,theta)
        error_list.append(err)
        if i!=0 and error_list[i-1]-error_list[i]<0.001:
            break
        grad = gradient(X,y,theta)
        
        theta = theta + lr*grad
    return theta ,error_list

In [18]:
theta , error_list = gradient_descent(X_new_train,Y_train)

<ipython-input-17-bbc978464c29>:2: RuntimeWarning: overflow encountered in exp
  return 1.0/(1.0 + np.exp(-x))
<ipython-input-17-bbc978464c29>:12: RuntimeWarning: divide by zero encountered in log
  e = -1*np.mean(y*np.log(hi)+(1-y)*np.log(1-hi))
<ipython-input-17-bbc978464c29>:12: RuntimeWarning: invalid value encountered in multiply
  e = -1*np.mean(y*np.log(hi)+(1-y)*np.log(1-hi))


In [19]:
theta

array([[ -1.65251362],
       [ 11.03630544],
       [ -1.32276951],
       [-10.82358495],
       [ -1.54270389],
       [ -1.96476529],
       [  1.32640771],
       [  0.60528332],
       [  0.28561083]])

In [21]:
def predict(X,theta):
    h = hypothesis(X,theta)
    output = np.zeros(h.shape)
    output[h>=0.5] = 1
    output = output.astype('int')
#     print(output[:5,:])
    return output
def accuracy(y_true, y_pred):
    accuracy = np.sum(y_true == y_pred) / len(y_true)
    return accuracy

In [22]:
y1 = predict(X_new_train,theta)

<ipython-input-17-bbc978464c29>:2: RuntimeWarning: overflow encountered in exp
  return 1.0/(1.0 + np.exp(-x))


In [23]:
accuracy(Y_train,y1)

0.6482084690553745

In [24]:
y1 = predict(X_new_test,theta)

<ipython-input-17-bbc978464c29>:2: RuntimeWarning: overflow encountered in exp
  return 1.0/(1.0 + np.exp(-x))


In [25]:
accuracy(Y_test,y1)

0.6623376623376623