In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
%matplotlib inline

In [2]:
from sklearn.model_selection import train_test_split
from sklearn import datasets

In [3]:
data = datasets.load_breast_cancer()

In [4]:
X = data.data
Y = data.target

In [5]:
print(X)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]


In [6]:
print(Y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 0 1 1 1 1 0 0 0 1 1
 1 1 0 1 0 1 0 1 1 1 0 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 1 0 0
 0 1 0 0 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 0 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1
 1 0 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 1 0 1 1 1 1 1 0 1 1
 0 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1
 1 1 1 1 1 1 0 1 0 1 1 0 

In [7]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.20)

In [8]:
print(X_train.shape,X_test.shape)
print(Y_train.shape,Y_test.shape)

(455, 30) (114, 30)
(455,) (114,)


Implementation

In [9]:
def sigmoid(x):
    return 1.0/(1.0 + np.exp(-x))

def hypothesis(X,theta):
    # X - entire array (m,n+1)
    # theta - np.array(n+1,1)
    return sigmoid(np.dot(X,theta))

In [10]:
def error(X,y,theta):

    hi = hypothesis(X,theta)
    e = -1*np.mean(y*np.log(hi)+(1-y)*np.log(1-hi))
    return e

def gradient(X,y,theta):

    hi = hypothesis(X,theta)
    grad = np.dot(X.T,(y-hi))
    return grad/X.shape[0]

def gradient_descent(X,y,lr=0.1,max_itr=500):
    n = X.shape[1]
    theta = np.zeros((n,1))
    
    error_list = []
    for i in range(max_itr):
        err = error(X,y,theta)
        error_list.append(err)
        if i!=0 and error_list[i-1]-error_list[i]<0.001:
            break
        grad = gradient(X,y,theta)
        
        theta = theta + lr*grad
    return theta ,error_list

In [11]:
ones = np.ones ((X_train.shape[0],1))
X_new_train = np.hstack((ones,X_train))
print(X_new_train)
print(X_new_train.shape)

[[ 1.      13.56    13.9     ...  0.0909   0.3065   0.08177]
 [ 1.      10.95    21.35    ...  0.1424   0.2964   0.09606]
 [ 1.      10.26    12.22    ...  0.06696  0.2937   0.07722]
 ...
 [ 1.      11.93    21.53    ...  0.07247  0.2438   0.08541]
 [ 1.      15.06    19.83    ...  0.2115   0.2834   0.08234]
 [ 1.      18.22    18.7     ...  0.1325   0.3021   0.07987]]
(455, 31)


In [12]:
ones = np.ones ((X_test.shape[0],1))
X_new_test = np.hstack((ones,X_test))
print(X_new_test)
print(X_new_test.shape)

[[ 1.      14.92    14.93    ...  0.1147   0.2688   0.08273]
 [ 1.      12.25    17.94    ...  0.08211  0.3113   0.08132]
 [ 1.      14.26    18.17    ...  0.0753   0.2636   0.07676]
 ...
 [ 1.      17.91    21.02    ...  0.1964   0.3245   0.1198 ]
 [ 1.      10.44    15.46    ...  0.04464  0.2615   0.08269]
 [ 1.      14.78    23.94    ...  0.1614   0.3321   0.08911]]
(114, 31)


In [13]:
Y_train = Y_train.reshape((-1,1))
Y_test = Y_test.reshape((-1,1))

In [14]:
print(X_train.shape,X_test.shape)
print(X_new_train.shape,X_new_test.shape)
print(Y_train.shape,Y_test.shape)

(455, 30) (114, 30)
(455, 31) (114, 31)
(455, 1) (114, 1)


In [15]:
theta , error_list = gradient_descent(X_new_train,Y_train)

<ipython-input-9-1e642e0925cb>:2: RuntimeWarning: overflow encountered in exp
  return 1.0/(1.0 + np.exp(-x))
<ipython-input-10-b28e9fad9edf>:4: RuntimeWarning: divide by zero encountered in log
  e = -1*np.mean(y*np.log(hi)+(1-y)*np.log(1-hi))
<ipython-input-10-b28e9fad9edf>:4: RuntimeWarning: invalid value encountered in multiply
  e = -1*np.mean(y*np.log(hi)+(1-y)*np.log(1-hi))


In [16]:
theta

array([[ 3.13579136e+00],
       [ 2.39018050e+01],
       [ 4.20141030e+01],
       [ 1.42637259e+02],
       [ 7.69496502e+01],
       [ 2.46299460e-01],
       [ 6.74032388e-03],
       [-2.74966632e-01],
       [-1.27737884e-01],
       [ 4.77657097e-01],
       [ 1.87683962e-01],
       [ 1.17425452e-01],
       [ 2.86912641e+00],
       [-9.52635067e-02],
       [-5.82308431e+01],
       [ 1.70335734e-02],
       [ 3.21994945e-03],
       [-8.43350586e-03],
       [ 3.08337024e-03],
       [ 5.05102045e-02],
       [ 6.05293750e-03],
       [ 2.49515209e+01],
       [ 5.46719021e+01],
       [ 1.45545934e+02],
       [-9.35535765e+01],
       [ 3.25648412e-01],
       [-8.44773878e-02],
       [-4.56325394e-01],
       [-1.03957819e-01],
       [ 7.06832613e-01],
       [ 2.02194339e-01]])

In [17]:
def predict(X,theta):
    h = hypothesis(X,theta)
    output = np.zeros(h.shape)
    output[h>=0.5] = 1
    output = output.astype('int')
#     print(output[:5,:])
    return output

In [18]:
predict(X_new_train,theta)

<ipython-input-9-1e642e0925cb>:2: RuntimeWarning: overflow encountered in exp
  return 1.0/(1.0 + np.exp(-x))


array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
    

In [19]:
XT_pred = predict(X_new_train,theta)
Xt_pred = predict(X_new_test,theta)

<ipython-input-9-1e642e0925cb>:2: RuntimeWarning: overflow encountered in exp
  return 1.0/(1.0 + np.exp(-x))


In [20]:
def accuracy(y_true, y_pred):
    accuracy = np.sum(y_true == y_pred) / len(y_true)
    return accuracy

In [21]:
print(XT_pred.shape)
print(Xt_pred.shape)

(455, 1)
(114, 1)


In [22]:
accuracy(Y_train,XT_pred)

0.9142857142857143

In [23]:
accuracy(Y_test,Xt_pred)

0.9385964912280702